# .prettierrc.toml
trailingComma = "all"
tabWidth = 4
semi = false
singleQuote = true
jsxSingleQuote = true
printWidth = 120
bracketSameLine = false
arrowParens = "always"
endOfLine = "crlf"
plugins = ["@prettier/plugin-pug"]