# .prettierrc.toml
trailingComma = "all"
tabWidth = 4
semi = false
singleQuote = true
jsxSingleQuote = true
printWidth = 120
bracketSameLine = false
arrowParens = "always"
endOfLine = "crlf"
plugins = [
    "@prettier/plugin-pug",
    "prettier-plugin-css-order"
]
cssDeclarationSorterKeepOverrides = false
cssDeclarationSorterCustomOrder = [
    "content",
    "position",
    "z-index",
    "top",
    "right",
    "bottom",
    "left",
    "transform",
    "transform-origin",
    "rotate",
    "translate",
    "scale",
    "float",
    "clear",
    "clip",
    "margin",
    "margin-top",
    "margin-right",
    "margin-bottom",
    "margin-left",
    "padding",
    "padding-top",
    "padding-right",
    "padding-bottom",
    "padding-left",
    "width",
    "min-width",
    "max-width",
    "height",
    "min-height",
    "max-height",
    "display",
    "flex",
    "flex-flow",
    "flex-basis",
    "flex-direction",
    "flex-grow",
    "flex-shrink",
    "flex-wrap",
    "justify-content",
    "order",
    "box-sizing",
    "align-content",
    "align-items",
    "align-self",
    "overflow",
    "overflow-x",
    "overflow-y",
    "pointer-events",
    "color",
    "font",
    "font-family",
    "font-size",
    "font-weight",
    "letter-spacing",
    "font-style",
    "font-variant",
    "font-size-adjust",
    "font-stretch",
    "line-height",
    "text-align",
    "text-align-last",
    "vertical-align",
    "white-space",
    "text-decoration",
    "text-emphasis",
    "text-emphasis-color",
    "text-emphasis-style",
    "text-emphasis-position",
    "text-indent",
    "text-justify",
    "word-spacing",
    "text-outline",
    "text-transform",
    "text-wrap",
    "text-overflow",
    "text-overflow-ellipsis",
    "text-overflow-mode",
    "word-wrap",
    "word-break",
    "tab-size",
    "hyphens",
    "cursor",
    "user-select",
    "box-shadow",
    "text-shadow",
    "opacity",
    "visibility",
    "background",
    "background-color",
    "background-image",
    "background-repeat",
    "background-attachment",
    "background-position",
    "background-position-x",
    "background-position-y",
    "background-clip",
    "background-origin",
    "background-size",
    "border-radius",
    "border",
    "border-width",
    "border-style",
    "border-color",
    "border-top",
    "border-top-width",
    "border-top-style",
    "border-top-color",
    "border-right",
    "border-right-width",
    "border-right-style",
    "border-right-color",
    "border-bottom",
    "border-bottom-width",
    "border-bottom-style",
    "border-bottom-color",
    "border-left",
    "border-left-width",
    "border-left-style",
    "border-left-color",
    "border-top-left-radius",
    "border-top-right-radius",
    "border-bottom-right-radius",
    "border-bottom-left-radius",
    "border-image",
    "border-image-source",
    "border-image-slice",
    "border-image-width",
    "border-image-outset",
    "border-image-repeat",
    "outline",
    "outline-width",
    "outline-style",
    "outline-color",
    "outline-offset",
    "list-style",
    "list-style-position",
    "list-style-type",
    "list-style-image",
    "resize",
    "transition",
    "transition-delay",
    "transition-timing-function",
    "transition-duration",
    "transition-property",
    "animation",
    "animation-name",
    "animation-duration",
    "animation-play-state",
    "animation-timing-function",
    "animation-delay",
    "animation-iteration-count",
    "animation-direction",
    "box-decoration-break",
    "zoom",
    "table-layout",
    "empty-cells",
    "caption-side",
    "border-spacing",
    "border-collapse",
    "quotes",
    "counter-reset",
    "counter-increment",
    "nav-index",
    "nav-up",
    "nav-right",
    "nav-down",
    "nav-left"
]