name: Build and deploy site by FTP

on:
  release:
    types: [released]
  workflow_dispatch:

permissions:
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.GITHUB_REF }}

      - name: Install pnpm
        uses: pnpm/action-setup@v3

      - name: Install Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'

      - run: |
          pnpm install
          pnpm run build

      - name: Upload build to artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist
          retention-days: 1
  deploy:
    runs-on: ubuntu-latest
    environment: deploy
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: dist

      - name: Copy files by FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          local-dir: ./dist/
          server-dir: .${{ vars.PATH }}/
          exclude: |
            **/*.html