name: Test build

on:
  pull_request:
    branches: ['main']
    paths-ignore:
      - '*.md'
      - '.idea'
      - '.github'

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3

      - name: Install Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'

      - run: |
          pnpm install
          pnpm run build